<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <title>Page-02</title>
    <link rel="stylesheet" href="../css/style-cam.css">
</head>
<body style="padding : 5%;">
    <form action="">
        <div class="row">
            <div class="col-md-2">
                <img src="img01.png" alt="" align = "right" style=" margin-top: 45px;">
            </div>
            <div class="col-md-8">
                <label>Kristal @ GiveKindness.asia</label>
                <label class="label_style" style="overflow: hidden;margin-left: 0px;">Hope you're holding up well, Mika Boshi!</label>
                <label class="label_style" style="margin-left: 0px;height:auto;">We'll need to you to learn more about you to proceed. THis helps us verify campaigns to ensure their authrntiity.</label>
                <label>Full name of beneficiary</label>
                <input type="text" id="inp_03" class="inp_2" >
                <label>Mobile number</label>
                <div style="display: flex;width: 100%;"> 
                    <select name="Mobile number" id="sel_01" class="inp_2" style="width: 80px;padding: 3px;" >
                        <option value="1">+1</option>
                        <option value="20">+20</option>
                        <option value="212">+212</option>
                        <option value="213">+213</option>
                        <option value="216">+218</option>
                        <option value="220">+220</option>
                        <option value="221">+221</option>
                        <option value="222">+222</option>
                        <option value="223">+223</option>
                        <option value="224">+224</option>
                        <option value="225">+225</option>
                        <option value="226">+226</option>
                        <option value="227">+227</option>
                        <option value="228">+228</option>
                        <option value="229">+229</option>
                        <option value="230">+230</option>
                        <option value="231">+231</option>
                        <option value="232">+232</option>
                        <option value="233">+233</option>
                        <option value="234">+234</option>
                        <option value="235">+235</option>
                        <option value="236">+237</option>
                        <option value="238">+238</option>
                        <option value="239">+239</option>
                        <option value="240">+240</option>
                        <option value="241">+241</option>
                        <option value="242">+242</option>
                        <option value="243">+243</option>
                        <option value="244">+244</option>
                        <option value="245">+245</option>
                        <option value="246">+246</option>
                        <option value="248">+248</option>
                        <option value="249">+249</option>
                        <option value="250">+250</option>
                        <option value="252">+252</option>
                        <option value="253">+253</option>
                        <option value="254">+254</option>
                        <option value="255">+255</option>
                        <option value="256">+256</option>
                        <option value="257">+257</option>
                        <option value="258">+258</option>
                        <option value="260">+260</option>
                        <option value="261">+261</option>
                        <option value="263">+263</option>
                        <option value="264">+264</option>
                        <option value="265">+265</option>
                        <option value="266">+266</option>
                        <option value="267">+267</option>
                        <option value="268">+268</option>
                        <option value="269">+269</option>
                        <option value="27">+27</option>
                        <option value="290">+290</option>
                        <option value="291">+291</option>
                        <option value="297">+297</option>
                        <option value="298">+298</option>
                        <option value="299">+299</option>
                        <option value="30">+30</option>
                        <option value="31">+31</option>
                        <option value="32">+32</option>
                        <option value="33">+33</option>
                        <option value="34">+34</option>
                        <option value="350">+350</option>
                        <option value="351">+351</option>
                        <option value="352">+352</option>
                        <option value="353">+353</option>
                        <option value="354">+354</option>
                        <option value="355">+355</option>
                        <option value="356">+356</option>
                        <option value="357">+357</option>
                        <option value="358">+358</option>
                        <option value="359">+359</option>
                        <option value="36">+36</option>
                        <option value="370">+370</option>
                        <option value="371">+371</option>
                        <option value="372">+373</option>
                        <option value="374">+374</option>
                        <option value="375">+375</option>
                        <option value="376">+376</option>
                        <option value="377">+377</option>
                        <option value="378">+378</option>
                        <option value="380">+380</option>
                        <option value="381">+381</option>
                        <option value="385">+385</option>
                        <option value="386">+386</option>
                        <option value="387">+387</option>
                        <option value="389">+389</option>
                        <option value="39">+39</option>
                        <option value="40">+40</option>
                        <option value="41">+41</option>
                        <option value="420">+420</option>
                        <option value="421">+421</option>
                        <option value="423">+423</option>
                        <option value="43">+43</option>
                        <option value="44">+44</option>
                        <option value="45">+45</option>
                        <option value="46">+46</option>
                        <option value="47">+47</option>
                        <option value="48">+48</option>
                        <option value="49">+49</option>
                        <option value="500">+500</option>
                        <option value="502">+502</option>
                        <option value="503">+503</option>
                        <option value="504">+504</option>
                        <option value="505">+505</option>
                        <option value="506">+506</option>
                        <option value="507">+507</option>
                        <option value="509">+509</option>
                        <option value="51">+51</option>
                        <option value="52">+52</option>
                        <option value="53">+53</option>
                        <option value="54">+54</option>
                        <option value="55">+55</option>
                        <option value="56">+56</option>
                        <option value="57">+57</option>
                        <option value="58">+58</option>
                        <option value="590">+590</option>
                        <option value="591">+591</option>
                        <option value="592">+592</option>
                        <option value="593">+593</option>
                        <option value="594">+594</option>
                        <option value="595">+595</option>
                        <option value="596">+596</option>
                        <option value="597">+597</option>
                        <option value="598">+598</option>
                        <option value="599">+599</option>
                        <option value="60">+60</option>
                        <option value="61">+61</option>
                        <option value="62">+62</option>
                        <option value="63">+63</option>
                        <option value="64">+64</option>
                        <option value="65" selected>+65</option>
                        <option value="66">+66</option>
                        <option value="670">+670</option>
                        <option value="673">+673</option>
                        <option value="674">+674</option>
                        <option value="675">+675</option>
                        <option value="676">+676</option>
                        <option value="677">+678</option>
                        <option value="679">+679</option>
                        <option value="680">+681</option>
                        <option value="682">+682</option>
                        <option value="683">+683</option>
                        <option value="685">+685</option>
                        <option value="686">+686</option>
                        <option value="687">+687</option>
                        <option value="688">+688</option>
                        <option value="689">+689</option>
                        <option value="690">+690</option>
                        <option value="691">+691</option>
                        <option value="692">+692</option>
                        <option value="7">+7</option>
                        <option value="81">+81</option>
                        <option value="82">+82</option>
                        <option value="84">+84</option>
                        <option value="850">+850</option>
                        <option value="852">+852</option>
                        <option value="853">+853</option>
                        <option value="855">+855</option>
                        <option value="856">+856</option>
                        <option value="86">+86</option>
                        <option value="880">+880</option>
                        <option value="886">+886</option>
                        <option value="90">+90</option>
                        <option value="91">+91</option>
                        <option value="92">+92</option>
                        <option value="93">+93</option>
                        <option value="94">+94</option>
                        <option value="95">+95</option>
                        <option value="960">+960</option>
                        <option value="961">+961</option>
                        <option value="962">+962</option>
                        <option value="963">+963</option>
                        <option value="964">+964</option>
                        <option value="965">+965</option>
                        <option value="966">+966</option>
                        <option value="967">+967</option>
                        <option value="968">+968</option>
                        <option value="970">+970</option>
                        <option value="971">+971</option>
                        <option value="972">+972</option>
                        <option value="973">+973</option>
                        <option value="974">+974</option>
                        <option value="975">+975</option>
                        <option value="976">+976</option>
                        <option value="977">+977</option>
                        <option value="98">+98</option>
                        <option value="992">+992</option>
                        <option value="993">+993</option>
                        <option value="994">+994</option>
                        <option value="995">+995</option>
                        <option value="996">+996</option>
                        <option value="998">+998</option>
                    </select>
                    <input type="text" id="inp_04" class="inp_2" style="width: 90%;margin-left: 3%;">
                </div>
                <label>Relationship woth beneficiary</label>
                <select name="Relationship" id="sel_02" class="inp_2" style="padding: 8px;">
                    <option value="1">I am the beneficiary</option>
                    <option value="2">I am not beneficiary</option>
                </select>
                <label >Country beneficiary is going to receive treatement</label>
                <select name="Country" id="sel_03" class="inp_2" style="padding: 8px;">
                    <option value="1">USA</option>
                    <option value="2">Canada</option>
                    <option value="20">Egypt</option>
                    <option value="212">Morocco</option>
                    <option value="213">Algeria</option>
                    <option value="216">Tunisia</option>
                    <option value="218">Libya</option>
                    <option value="220">Gambia</option>
                    <option value="221">Senegal</option>
                    <option value="222">Mauritania</option>
                    <option value="223">Mali</option>
                    <option value="224">Guinea</option>
                    <option value="225">Ivory Coast</option>
                    <option value="225">Burkina Faso</option>
                    <option value="227">Niger</option>
                    <option value="228">Togo</option>
                    <option value="229">Benin</option>
                    <option value="230">Mauritius</option>
                    <option value="231">Liberia</option>
                    <option value="232">Sierra Leone</option>
                    <option value="233">Ghana</option>
                    <option value="234">Nigeria</option>
                    <option value="235">Chad</option>
                    <option value="236">Central African Republic</option>
                    <option value="237">Cameroon</option>
                    <option value="238">Cape Verde</option>
                    <option value="239">Sao Tome and Principe</option>
                    <option value="240">Equatorial Guinea</option>
                    <option value="241">Gabon</option>
                    <option value="242">Congo-Brazzaville</option>
                    <option value="243">Congo-Kinshasa</option>
                    <option value="244">Angola</option>
                    <option value="245">Guinea-Bissau</option>
                    <option value="246">British Indian Ocean Territory</option>
                    <option value="248">Seychelles</option>
                    <option value="249">Sudan</option>
                    <option value="250">Rwanda</option>
                    <option value="252">Somalia</option>
                    <option value="253">Djibouti</option>
                    <option value="254">Kenya</option>
                    <option value="255">Tanzania</option>
                    <option value="256">Uganda</option>
                    <option value="257">Burundi</option>
                    <option value="258">Mozambique</option>
                    <option value="260">Zambia</option>
                    <option value="261">Madagascar</option>
                    <option value="263">Zimbabwe</option>
                    <option value="264">Namibia</option>
                    <option value="265">Malawi</option>
                    <option value="266">Lesotho</option>
                    <option value="267">Botswana</option>
                    <option value="268">Swaziland</option>
                    <option value="269">Mayotte</option>
                    <option value="27">South Africa</option>
                    <option value="290">Saint Helena</option>
                    <option value="291">Eritrea</option>
                    <option value="297">Aruba</option>
                    <option value="298">Faroe Islands</option>
                    <option value="299">Greenland</option>
                    <option value="30">Greece</option>
                    <option value="31">Netherlands</option>
                    <option value="32">Belgium</option>
                    <option value="33">France</option>
                    <option value="34">Spain</option>
                    <option value="350">Gibraltar</option>
                    <option value="351">Portugal</option>
                    <option value="352">Luxembourg</option>
                    <option value="353">Ireland</option>
                    <option value="354">Iceland</option>
                    <option value="355">Albania</option>
                    <option value="356">Malta</option>
                    <option value="357">Cyprus</option>
                    <option value="358">Finland</option>
                    <option value="359">Bulgaria</option>
                    <option value="36">Hungary</option>
                    <option value="370">Lithuania</option>
                    <option value="371">Latvia</option>
                    <option value="372">Estonia</option>
                    <option value="373">Moldova</option>
                    <option value="374">Armenia</option>
                    <option value="375">Belarus</option>
                    <option value="376">Andorra</option>
                    <option value="377">Monaco</option>
                    <option value="378">San Marino</option>
                    <option value="380">Ukraine</option>
                    <option value="381">Serbia</option>
                    <option value="385">Croatia</option>
                    <option value="386">Slovenia</option>
                    <option value="387">Bosnia and Herzegovina</option>
                    <option value="389">Macedonia</option>
                    <option value="39">Italy</option>
                    <option value="40">Romania</option>
                    <option value="41">Switzerland</option>
                    <option value="420">Czech Republic</option>
                    <option value="421">Slovakia</option>
                    <option value="423">Liechtenstein</option>
                    <option value="43">Austria</option>
                    <option value="44">United Kingdom</option>
                    <option value="45">Denmark</option>
                    <option value="46">Sweden</option>
                    <option value="47">Norway</option>
                    <option value="48">Poland</option>
                    <option value="49">Germany</option>
                    <option value="500">Falkland Islands</option>
                    <option value="502">Guatemala</option>
                    <option value="503">El Salvador</option>
                    <option value="504">Honduras</option>
                    <option value="505">Nicaragua</option>
                    <option value="506">Costa Rica</option>
                    <option value="507">Panama</option>
                    <option value="509">Haiti</option>
                    <option value="51">Peru</option>
                    <option value="52">Mexico</option>
                    <option value="53">Cuba</option>
                    <option value="54">Argentina</option>
                    <option value="55">Brazil</option>
                    <option value="56">Chile</option>
                    <option value="57">Colombia</option>
                    <option value="58">Venezuela</option>
                    <option value="590">Guadeloupe</option>
                    <option value="591">Bolivia</option>
                    <option value="592">Guyana</option>
                    <option value="593">Ecuador</option>
                    <option value="594">French Guiana</option>
                    <option value="595">Paraguay</option>
                    <option value="596">Martinique</option>
                    <option value="597">Suriname</option>
                    <option value="598">Uruguay</option>
                    <option value="599">Netherlands Antilles</option>
                    <option value="60">Malaysia</option>
                    <option value="61">Australia</option>
                    <option value="62">Indonesia</option>
                    <option value="63">Philippines</option>
                    <option value="64">New Zealand</option>
                    <option value="65" selected>Singapore</option>
                    <option value="66">Thailand</option>
                    <option value="670">Timor-Leste</option>
                    <option value="673">Brunei</option>
                    <option value="674">Nauru</option>
                    <option value="675">Papua New Guinea</option>
                    <option value="676">Tonga</option>
                    <option value="677">Solomon Islands</option>
                    <option value="678">Vanuatu</option>
                    <option value="679">Fiji</option>
                    <option value="680">Palau</option>
                    <option value="681">Wallis and Futuna</option>
                    <option value="682">Cook Islands</option>
                    <option value="683">Niue</option>
                    <option value="685">Samoa</option>
                    <option value="686">Kiribati</option>
                    <option value="687">New Caledonia</option>
                    <option value="688">Tuvalu</option>
                    <option value="689">French Polynesia</option>
                    <option value="690">Tokelau</option>
                    <option value="691">Micronesia</option>
                    <option value="692">Marshall Islands</option>
                    <option value="7">Kazakhstan</option>
                    <option value="7">Russia</option>
                    <option value="81">Japan</option>
                    <option value="82">South Korea</option>
                    <option value="84">Vietnam</option>
                    <option value="850">North Korea</option>
                    <option value="852">Hong Kong</option>
                    <option value="853">Macau</option>
                    <option value="855">Cambodia</option>
                    <option value="856">Laos</option>
                    <option value="86">China</option>
                    <option value="880">Bangladesh</option>
                    <option value="886">Taiwan</option>
                    <option value="90">Turkey</option>
                    <option value="91">India</option>
                    <option value="92">Pakistan</option>
                    <option value="93">Afghanistan</option>
                    <option value="94">Sri Lanka</option>
                    <option value="95">Burma</option>
                    <option value="960">Maldives</option>
                    <option value="961">Lebanon</option>
                    <option value="962">Jordan</option>
                    <option value="963">Syria</option>
                    <option value="964">Iraq</option>
                    <option value="965">Kuwait</option>
                    <option value="966">Saudi Arabia</option>
                    <option value="967">Yemen</option>
                    <option value="968">Oman</option>
                    <option value="970">Palestinian Territory</option>
                    <option value="971">United Arab Emirates</option>
                    <option value="972">Israel</option>
                    <option value="973">Bahrain</option>
                    <option value="974">Qatar</option>
                    <option value="975">Bhutan</option>
                    <option value="976">Mongolia</option>
                    <option value="977">Nepal</option>
                    <option value="98">Iran</option>
                    <option value="992">Tajikistan</option>
                    <option value="993">Turkmenistan</option>
                    <option value="994">Azerbaijan</option>
                    <option value="995">Georgia</option>
                    <option value="996">Kyrgyzstan</option>
                    <option value="998">Uzbekistan</option>
                </select>
                <label >Age group of beneficiary</label>
                <select name="Age" id="sel_04" class="inp_2" style="padding: 8px;">
                    <option value="1">Newborn</option>
                    <option value="2">Infant</option>
                    <option value="3">Toddler</option>
                    <option value="4">Kids</option>
                    <option value="5" selected>Adult</option>
                </select>
                <label>Medical Condition</label>
                <input type="text" id="inp_05" class="inp_2" >
                <label>Medical Document Upload(Snapshot of the first page of medical consultant report)</label>
                <select name="Age" id="sel_05" class="inp_2" style="padding: 3px;padding-left:15px;">
                    <option value="1"></option>
                </select>
                <input type="submit" id="inp_06" value="NEXT" class="inp_submit">
            </div>
        </div>
    </form>
</body>
</html>